### ISSUE TITLE
current code? and github or gitlab?

### ISSUE THREAD

**Issue by Blub** [myrrlyn/endian_trait#1]
To reduce dependency compile time I'd like to bump this to syn/quote/proc-macro2 1.0, but the code here and on gitlab seems outdated (crates.io has version 0.6)...
Where's the code's current home?

edit: not too many changes required:
https://github.com/Blub/endian_trait/commits/syn_quote_proc-macro2_1.0

the Cargo.toml diff conflicts with 0.6 though due to `[dependency]` vs `[dependency.foo]` changes.

**Comment by myrrlyn** [comment]
Hi! Thanks for the issue; I'd honestly forgotten about this crate and haven't touched it in a while. I'll update the macros and publish as `0.7`, probably sometime in the next 24 hours.

**Comment by Blub** [comment]
You could consider bumping to 1.0 given that there are probably not going to be many API changes in the future ;-)
The only real change I expect in the somewhat near future would be changing the array handling code to use const generics once those become stable which would be mostly a bump to the minimum required rustc version.

**Comment by myrrlyn** [comment]
Current master will get published as `1.0` in the near future; I want to review it after I'm no longer on a cross-continental train before publishing.
